/* Service Worker — auto-generated by specbuild PWA module.
   Caches all specification assets for offline viewing. */

const CACHE_NAME = 'spec-av2-isobmff_Spec';
const ASSETS = [
  ".",
  "av2-isobmff_Spec.pdf",
  "css/base.css",
  "css/custom.css",
  "css/dark-mode.css",
  "css/definition-tooltips.css",
  "css/equation-tooltips.css",
  "css/figure-table-tooltips.css",
  "css/multipage-navigation.css",
  "css/multipage-search.css",
  "css/pdf-fixes.css",
  "css/print.css",
  "css/specbuild.css",
  "css/syntax-tooltips.css",
  "css/syntax_browser.css",
  "css/table-modal.css",
  "css/w3c-cache/UD-watermark-light-draft.svg",
  "css/w3c-cache/UD-watermark-light-unofficial.svg",
  "css/w3c-cache/UD-watermark.svg",
  "css/w3c-cache/W3C-UD.css",
  "css/w3c-cache/W3C-logo.svg",
  "css/w3c-cache/base.css",
  "css/weasyprint.css",
  "images/icon-192x192.svg",
  "images/icon-512x512.svg",
  "index.html",
  "js/dark-mode.js",
  "js/definition-tooltips.js",
  "js/equation-tooltips.js",
  "js/figure-table-tooltips.js",
  "js/multipage-navigation.js",
  "js/multipage-search.js",
  "js/syntax-tooltips.js",
  "js/syntax_browser.js",
  "js/table-modal.js",
  "js/table-numbering.js",
  "manifest.json"
];

self.addEventListener('install', function (event) {
  event.waitUntil(
    caches.open(CACHE_NAME).then(function (cache) {
      return cache.addAll(ASSETS);
    })
  );
  self.skipWaiting();
});

self.addEventListener('activate', function (event) {
  event.waitUntil(
    caches.keys().then(function (names) {
      return Promise.all(
        names.filter(function (n) { return n !== CACHE_NAME; })
             .map(function (n) { return caches.delete(n); })
      );
    })
  );
  self.clients.claim();
});

self.addEventListener('fetch', function (event) {
  event.respondWith(
    caches.match(event.request).then(function (cached) {
      return cached || fetch(event.request);
    })
  );
});
